### ISSUE TITLE
Wrong last stable nucleotide for a deletion in GRCh37 to GRCh38 conversion

### ISSUE THREAD

**Issue by ivan-mh** [liguowang/CrossMap#44]
Dear Authors,

Thank you for this great tool!

I have been testing CrossMap with DBSNP v151 data and found one type of conversion that doesn't look correct. 

For DBSNP rs202079816: given chr22:28084772 **C**T>**C** on GRCh37 as input, CrossMap produces chr22:27688775 **G**T>**C** on GRCh38 as output, where I would expect chr22:27688775 **G**T>**G** on GRCh38. 

Here the ALT seems not to be set to the last stable nucleotide (**G**) in GRCh38. Note that the last stable nucleotide differ between the two assemblies GRCh37 (**C**) and GRCh38 (**G**). Does this affect only deletions or also other variant types? 

I used CrossMap (v0.6.1) and chain file: ftp://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh37_to_GRCh38.chain.gz

Many Thanks,
Ivan

**Comment by liguowang** [comment]
Hi Ivan,
Maybe I did not fully understand the problem here. CrossMap only updates the reference allele but not the alternative allele. So here CT>**C**   =>  GT>**G**, Why C was changed into G? Is this variant on the "-" strand? What you mean "the last stable nucleotide" ?

**Comment by ivan-mh** [comment]
Hi Liguo,

Thank you for your reply and sorry for my previous imprecise description. I think, this is probably a bug in CrossMap, I have found a similar issue for 930 DBSNP variants. Below, you can find one example:       

The input VCF variant, GRCh37 coordinates:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO 
chr22	28084772	rs202079816	**C**T	**C**	.	.	RS=202079816

The output VCF variant in the CrossMap output, GRCh38 coordinates: 
chr22	27688775	rs202079816	**G**T	**C**	.	.	RS=202079816

Expected VCF variant, GRCh38 coordinates:
chr22	27688775	rs202079816	**G**T	**G**	.	.	RS=202079816 

Corresponding mapping represented by the chain file, when running highly appreciated: CrossMap.py viewchain GRCh37_to_GRCh38.chain.gz
chr22	28067972	28085507	+	22	27671975	27689510	+
 
In the reference genome GRCh37 at position chr22:28084773, there is a T. In GRCh38 at position chr22:27688776 there is also a T.

In GRCh37 at position chr22:28084772, there is a **C**. In GRCh38 at position chr22:27688775 there is a **G**.

When running the same input variant through GATK LiftoverVcf, the variant gets rejected with: MismatchedRefAllele, which I would understand, as there is a mismatch in the reference allele (**C** vs **G**).

For deletions, according to the VCF standard, the first nucleotide in REF and ALT correspond to the nucleotide at POS in the reference genome, I would therefore expect that in the case the first nucleotide in REF is adjusted by CrossMap, then the first nucleotide in ALT should also be set to the same nucleotide (i.e. **G** in the example above).

To conclude, I think that this variant should either be rejected or the nucleotide in the ALT should be set to **G**. Where, I would prefer to still map this variant with corrected ALT. Or I am missing something and a deletion can turn into a delins?

Many Thanks,
Ivan

**Comment by liguowang** [comment]
Hi Ivan, 
Thank you very much for clarifying. This makes sense to me now.  We will update and release a new version ASAP. 

Liguo

**Comment by ivan-mh** [comment]
Hi Liguo,

Thank you very much, I am looking forward to the new version. Today, I think I have found another issue: https://github.com/liguowang/CrossMap/issues/47

Best wishes,
Ivan

**Comment by ivan-mh** [comment]
Hi Liguo,

Thank you very much for releasing CrossMap version 0.6.3. I now run the full test with more than 600 million DBSNP v151 variants. 

With CrossMap version 0.6.1, I found 930 problematic variants targeted in this issue. With the new version, I am still unfortunately getting 109 problematic variants, which is a big improvement, although the problem now seems to be for variants on the negative strand on GRCh38. 

Example: 
![image](https://user-images.githubusercontent.com/54623677/158888970-d5743972-4f71-4f90-b74f-35170fe5d509.png)

For GRCh37 input variant:
chr7	61879851	rs1223781306	A	AC	.	.	.

I would expect according to DBSNP on GRCh38:
chr7	62217710	rs1223781306	T	TG	.	.	.

Nevertheless, I got from CrossMap on GRCh38:
chr7	62217710	.	T	GA	.	.	.

The problem seems to be that an insertion turns into a delins, which does not seem to be correct. The REF and ALT should start with the REF nucleotide T at position chr7:62217710 on GRCh38. Would it be possible to fix also such variants? 

Attached is a file containing all the 109 problematic variants, where INFO.GRCh37 is the input GRCh37 variant in format CHROM:POS:REF:ALT. Fields CHROM, POS, REF, ALT contain the CrossMap v0.6.3 output on GRCh38. The ID contains the expected mapping according to DBSNP on GRCh38 in format: s;RS;GENE;CHROM:POS:REF:ALT, where the ALT can contain
multiple values for one RS identifier. I am also aware that not all expected DBSNP variant mappings are correct according to the chain file I am using, where I am using: ftp://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh37_to_GRCh38.chain.gz   

Best wishes,
Ivan
[CrossMap_v063_issue_44.txt](https://github.com/liguowang/CrossMap/files/8291611/CrossMap_v063_issue_44.txt)

**Comment by liguowang** [comment]
Thanks, Ivan. This is very helpful. I will look into these issues.

**Comment by liguowang** [comment]
We will try to address this issue in a few weeks, sorry all of us have busy schedules. will let you know...

**Comment by ivan-mh** [comment]
Hi Liguo,

Thank you for releasing the 0.6.4 CrossMap version. 

I tested the lift over from GRCh37 to GRCh38 using ensembl chain files with ~660 million DBSNP v151 variants and the results were identical to the 0.6.3 CrossMap version.

Unfortunately, the issue described here and in #47 have not yet been fixed. I understand you are very busy, but do you have an estimate when it could be fixed?   

Many Thanks,
Ivan

**Comment by pintoa1-mskcc** [comment]
I too am having issues where insertions become deletions. It seems when using Crossmap MAF, the tool doesnt actually look at the original reference (-) and just shoves in the asssemblies reference. This causes some insertions to become SNVs or deletions.

**Comment by Stikus** [comment]
Hello, I've experienced issues whose origin are from these changes (I think) - that's why I'm posing here (issue should be reopened maybe?):

I've checked [VCF spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf) and found what @ivan-mh was talking about - if we have `GGT` `REF` and `G-T` `ALT` - it isn't `chr1:149032050 GT->T` - it is `chr1:149032049 GG->G`.

![image](https://user-images.githubusercontent.com/41360525/194832759-6785edfa-018f-4c26-b2ec-bf731254a673.png)


But here is the problem - before we have incorrectly stated indels:
```
chr1	149032050	indel.6062	GT	T	.	PASS	.	GT:GQ	0/0:3
chr1	148974590	indel.6073	AG	G	.	PASS	.	GT:GQ	0/0:3
chr1	148953847	indel.6081	CA	A	.	PASS	.	GT:GQ	0/0:2
chr1	148953579	indel.6083	GA	A	.	PASS	.	GT:GQ	0/0:3
chr1	145994150	indel.6100	C	TC	.	PASS	.	GT:GQ	0/0:2
chr1	145994018	indel.6101	CAGTATA	A	.	PASS	.	GT:GQ	0/0:2
chr1	145994017	indel.6102	T	CT	.	PASS	.	GT:GQ	0/0:2
chr1	145892823	indel.6130	T	CTCTTT	.	PASS	.	GT:GQ	0/0:3
chr1	145873621	indel.6147	TG	G	.	PASS	.	GT:GQ	0/0:2
chr1	145873607	indel.6148	G	TG	.	PASS	.	GT:GQ	0/0:3
chr1	145872926	1KG_1_145562155	T	CCTT	.	PASS	.	GT:GQ	0/0:2
chr1	145867368	indel.6157	TG	G	.	PASS	.	GT:GQ	0/0:3
chr1	145838109	indel.6181	TAG	G	.	PASS	.	GT:GQ	0/0:2
chr1	145826589	indel.6187	AC	C	.	PASS	.	GT:GQ	0/0:3
chr1	145736151	indel.6189	CGTAAGCACCCCAAGCA	A	.	PASS	.	GT:GQ	0/0:3
chr1	145731005	indel.6192	GT	T	.	PASS	.	GT:GQ	0/0:3
chr1	145686476	indel.6198	C	AC	.	PASS	.	GT:GQ	0/0:6
chr1	144423146	var_1_148594506	TG	G	.	PASS	.	GT:GQ	0/0:2
chr1	206016023	indel.9616	G	AGGAG	.	PASS	.	GT:GQ	0/0:3
chr10	47355450	indel.12475	TG	G	.	PASS	.	GT:GQ	0/0:2
chr10	47353516	indel.12476	GT	T	.	PASS	.	GT:GQ	0/0:3
chr10	46010865	indel.12613	TC	C	.	PASS	.	GT:GQ	0/0:2
chr11	54707629	indel.17968	G	TG	.	PASS	.	GT:GQ	0/0:3
chr11	54707548	indel.17970	CT	T	.	PASS	.	GT:GQ	0/0:3
chr11	54603389	indel.17972	T	AT	.	PASS	.	GT:GQ	0/0:2
chr11	54603365	indel.17973	G	CAG	.	PASS	.	GT:GQ	0/0:2
chr15	23030984	indel.34217	GTTGA	A	.	PASS	.	GT:GQ	0/0:2
chr15	23021965	indel.34223	C	GC	.	PASS	.	GT:GQ	0/0:3
chr15	23011305	indel.34227	G	AG	.	PASS	.	GT:GQ	0/0:2
chr21	10592374	indel.69325	GT	T	.	PASS	.	GT:GQ	0/0:1
```

But now we have ... I can't understand, what do we have now. Some random alleles.
```
chr1	149032050	indel.6062	GT	C	.	PASS	.	GT:GQ	0/0:3
chr1	148974590	indel.6073	AG	T	.	PASS	.	GT:GQ	0/0:3
chr1	148953847	indel.6081	CA	G	.	PASS	.	GT:GQ	0/0:2
chr1	148953579	indel.6083	GA	C	.	PASS	.	GT:GQ	0/0:3
chr1	145994150	indel.6100	C	TG	.	PASS	.	GT:GQ	0/0:2
chr1	145994018	indel.6101	CAGTATA	G	.	PASS	.	GT:GQ	0/0:2
chr1	145994017	indel.6102	T	CA	.	PASS	.	GT:GQ	0/0:2
chr1	145892823	indel.6130	T	CTCTTA	.	PASS	.	GT:GQ	0/0:3
chr1	145873621	indel.6147	TG	A	.	PASS	.	GT:GQ	0/0:2
chr1	145873607	indel.6148	G	TC	.	PASS	.	GT:GQ	0/0:3
chr1	145872926	1KG_1_145562155	T	CCTA	.	PASS	.	GT:GQ	0/0:2
chr1	145867368	indel.6157	TG	A	.	PASS	.	GT:GQ	0/0:3
chr1	145838109	indel.6181	TAG	A	.	PASS	.	GT:GQ	0/0:2
chr1	145826589	indel.6187	AC	T	.	PASS	.	GT:GQ	0/0:3
chr1	145736151	indel.6189	CGTAAGCACCCCAAGCA	G	.	PASS	.	GT:GQ	0/0:3
chr1	145731005	indel.6192	GT	C	.	PASS	.	GT:GQ	0/0:3
chr1	145686476	indel.6198	C	AG	.	PASS	.	GT:GQ	0/0:6
chr1	144423146	var_1_148594506	TG	A	.	PASS	.	GT:GQ	0/0:2
chr1	206016023	indel.9616	G	AGGAC	.	PASS	.	GT:GQ	0/0:3
chr10	47355450	indel.12475	TG	A	.	PASS	.	GT:GQ	0/0:2
chr10	47353516	indel.12476	GT	C	.	PASS	.	GT:GQ	0/0:3
chr10	46010865	indel.12613	TC	A	.	PASS	.	GT:GQ	0/0:2
chr11	54707629	indel.17968	G	TC	.	PASS	.	GT:GQ	0/0:3
chr11	54707548	indel.17970	CT	G	.	PASS	.	GT:GQ	0/0:3
chr11	54603389	indel.17972	T	AA	.	PASS	.	GT:GQ	0/0:2
chr11	54603365	indel.17973	G	CAC	.	PASS	.	GT:GQ	0/0:2
chr15	23030984	indel.34217	GTTGA	C	.	PASS	.	GT:GQ	0/0:2
chr15	23021965	indel.34223	C	GG	.	PASS	.	GT:GQ	0/0:3
chr15	23011305	indel.34227	G	AC	.	PASS	.	GT:GQ	0/0:2
chr21	10592374	indel.69325	GT	C	.	PASS	.	GT:GQ	0/0:1
```

Fortunately its only ~20 indels across 10000 indels in our data but this is still a problem.

Btw - I'm using `https://hgdownload.cse.ucsc.edu/goldenpath/hg19/liftOver/hg19ToHg38.over.chain.gz` chain - should I use `ftp://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh37_to_GRCh38.chain.gz` instead?

**Comment by liguowang** [comment]
To be honest, I don't know which one (**chr1:149032050 GT->T** or **chr1:149032049 GG->G**) is correct. But for the 2nd one (chr1:149032049 GG->G) would NOT tell you which reference G is deleted. right?

**Comment by Stikus** [comment]
According to spec - first one is correct. And how can you differentiate which one G is deleted in nature? Aren't they the same?

**Comment by liguowang** [comment]
I agree. The 2nd one follows the VCF specification. This should be an easy fix.

**Comment by pintoa1-mskcc** [comment]
In regard to CROSSMAP MAF and how it handles indels, shouldI open a separate issue?

**Comment by liguowang** [comment]
> In regard to CROSSMAP MAF and how it handles indels, shouldI open a separate issue?

We will do the same way as VCF files

**Comment by liguowang** [comment]
@ivan-mh ,  Sorry for the long delay.  The issue (#47) is a little bit
complicated. Could you please check if this beta version fixes the problem?
I hope this change will not mess up other variants (It does work for
rs768155704). Thanks very much.

https://drive.google.com/file/d/16HsEz-CcxOgjuzN5-9Utx_Txn8D_vOAr/view?usp=sharing

**Comment by Stikus** [comment]
@liguowang Hello, do we have fix for this issue?

**Comment by liguowang** [comment]
> @liguowang Hello, do we have fix for this issue?

please download the code (https://drive.google.com/file/d/16HsEz-CcxOgjuzN5-9Utx_Txn8D_vOAr/view?usp=sharing) to see if the problem is solved or not. Thanks

**Comment by Stikus** [comment]
I've installed `b0` version:
```
#11 [ 7/10] RUN cd "/soft"     && wget -q .../distr/CrossMap-0.6.5b0.tar.gz -O "/soft/CrossMap-0.6.5b0.tar.gz"     && tar -xzf "/soft/CrossMap-0.6.5b0.tar.gz"     && cd "/soft/CrossMap-0.6.5b0"     && pip3 install --no-cache-dir .
#11 0.644 Processing /soft/CrossMap-0.6.5b0
#11 0.645   Preparing metadata (setup.py): started
#11 0.850   Preparing metadata (setup.py): finished with status 'done'
#11 0.857 Requirement already satisfied: cython>=0.17 in /usr/local/lib/python3.7/dist-packages (from CrossMap==0.6.5b0) (0.29.34)
#11 0.858 Requirement already satisfied: pysam in /usr/local/lib/python3.7/dist-packages (from CrossMap==0.6.5b0) (0.21.0)
#11 1.185 Collecting bx-python
#11 1.385   Downloading bx_python-0.9.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
#11 1.668      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 15.4 MB/s eta 0:00:00
#11 1.829 Collecting pyBigWig
#11 1.884   Downloading pyBigWig-0.3.22-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (192 kB)
#11 1.888      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.5/192.5 kB 150.1 MB/s eta 0:00:00
#11 1.892 Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from bx-python->CrossMap==0.6.5b0) (1.21.6)
#11 1.896 Building wheels for collected packages: CrossMap
#11 1.897   Building wheel for CrossMap (setup.py): started
#11 2.193   Building wheel for CrossMap (setup.py): finished with status 'done'
#11 2.194   Created wheel for CrossMap: filename=CrossMap-0.6.5b0-py3-none-any.whl size=39444 sha256=8df307f6559be4273b5f56d539dd40467e21fa33595e58254756fa319683226e
#11 2.194   Stored in directory: /tmp/pip-ephem-wheel-cache-miuf2i4c/wheels/f6/e7/83/788fdaa5286f29f5194ab664a6c17dfe88f61b8dd8a70f19be
#11 2.196 Successfully built CrossMap
#11 2.241 Installing collected packages: pyBigWig, bx-python, CrossMap
#11 2.641 Successfully installed CrossMap-0.6.5b0 bx-python-0.9.0 pyBigWig-0.3.22
```

Nothing changed:
```
< chr1	149032050	indel.6062	GT	T	.	PASS	.	GT:GQ	0/0:3
---
> chr1	149032050	indel.6062	GT	C	.	PASS	.	GT:GQ	0/0:3
25383c25383
< chr1	148974590	indel.6073	AG	G	.	PASS	.	GT:GQ	0/0:3
---
> chr1	148974590	indel.6073	AG	T	.	PASS	.	GT:GQ	0/0:3
25408c25408
```

**Comment by Stikus** [comment]
@liguowang Issue is not fixed - do you have any other ides how to fix it?

**Comment by liguowang** [comment]
> @liguowang Issue is not fixed - do you have any other ides how to fix it?

I will see if I have some time this evening to look into this issue.

**Comment by Stikus** [comment]
@liguowang If you need help with fix or feedback - we can try, but we don't know where to look at now.

**Comment by liguowang** [comment]
According to [VCF specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf) (Section 5.1.1 Example 1), the *first nucleotide of ALT* should always be the same as *the first nucleotide of REF*.  right? If this is true, the variants below are NOT valid:

chr1	149032050	indel.6062	GT	T	.	PASS	.	GT:GQ	0/0:3
chr1	148974590	indel.6073	AG	G	.	PASS	.	GT:GQ	0/0:3
chr1	148953847	indel.6081	CA	A	.	PASS	.	GT:GQ	0/0:2
chr1	148953579	indel.6083	GA	A	.	PASS	.	GT:GQ	0/0:3
...

**Comment by Stikus** [comment]
Hello again, any chance that you'll find time to fix?

**Comment by serge2016** [comment]
@liguowang Hello! Any news? This is important for me too. Help us, please!

**Comment by liguowang** [comment]
> @liguowang Hello! Any news? This is important for me too. Help us, please!
This is not an easy fix. I just released v0.6.6, but this version still has the same issue probably. I will take a close look after vacation (August 3). Sorry for the delay.

**Comment by serge2016** [comment]
> > This is not an easy fix. I just released v0.6.6, but this version still has the same issue probably. I will take a close look after vacation (August 3). Sorry for the delay.

Thank you very much!

**Comment by serge2016** [comment]
Sorry, @liguowang, there is no `v0.6.6` in this repo. There are 3 new commits, but the version is still not 0.6.6:

- [ ] https://github.com/liguowang/CrossMap/blob/master/build/scripts-3.8/CrossMap.py#L32 (0.6.4)
- [ ] https://github.com/liguowang/CrossMap/blob/master/build/scripts-3.7/CrossMap.py#L29 (0.4.3)
- [ ] https://github.com/liguowang/CrossMap/blob/master/docs/conf.py#L56 (0.6.5)
- [ ] https://github.com/liguowang/CrossMap/blob/master/docs/index.rst (0.6.4)
- [ ] https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/genindex.html#L8 + https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/genindex.html#L25 + https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/genindex.html#L69 (0.6.4)
- [ ] https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/index.html#L8 + https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/index.html#L25 + https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/index.html#L50 (0.6.4)
- [ ] https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/objects.inv#L3 (0.6.4)
- [ ] https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/search.html#L8 + https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/search.html#L30 + https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/search.html#L78
- [ ] https://github.com/liguowang/CrossMap/blob/master/docs/_build/html/_sources/index.rst.txt (0.6.4)
- [ ] https://github.com/liguowang/CrossMap/blob/master/setup.py#L12 (0.6.5)
- [ ] https://github.com/liguowang/CrossMap/blob/master/PKG-INFO#L3 (0.2.6)
- [ ] https://github.com/liguowang/CrossMap/blob/master/bin/CrossMap.py#L33 (0.6.5)
- [ ]

**Comment by Stikus** [comment]
I've found v0.6.6: https://pypi.org/project/CrossMap/0.6.6/

Issue is still here, @liguowang is correct. Happy vacation :)

**Comment by Stikus** [comment]
Hello again, @liguowang, I hope your vacation went well. What about our problem?

**Comment by Stikus** [comment]
@liguowang Hello, sorry for another ping, but we still cannot use latest CrossMap due to this problem.

**Comment by liguowang** [comment]
> @liguowang Hello, sorry for another ping, but we still cannot use latest CrossMap due to this problem.

Could you please refresh my mind again by providing some examples? (and your expected results). Thanks a lot.

**Comment by Stikus** [comment]
I've quoted the relevant part of the discussion with links:

@Stikus [link](https://github.com/liguowang/CrossMap/issues/44#issuecomment-1273021084)
> Hello, I've experienced issues whose origin are from these changes (I think) - that's why I'm posing here (issue should be reopened maybe?):
> 
> I've checked [VCF spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf) and found what @ivan-mh was talking about - if we have `GGT` `REF` and `G-T` `ALT` - it isn't `chr1:149032050 GT->T` - it is `chr1:149032049 GG->G`.
> 
> ![image](https://user-images.githubusercontent.com/41360525/194832759-6785edfa-018f-4c26-b2ec-bf731254a673.png)
> 
> But here is the problem - before we have incorrectly stated indels:
> 
> ```
> chr1	149032050	indel.6062	GT	T	.	PASS	.	GT:GQ	0/0:3
> chr1	148974590	indel.6073	AG	G	.	PASS	.	GT:GQ	0/0:3
> chr1	148953847	indel.6081	CA	A	.	PASS	.	GT:GQ	0/0:2
> chr1	148953579	indel.6083	GA	A	.	PASS	.	GT:GQ	0/0:3
> chr1	145994150	indel.6100	C	TC	.	PASS	.	GT:GQ	0/0:2
> chr1	145994018	indel.6101	CAGTATA	A	.	PASS	.	GT:GQ	0/0:2
> chr1	145994017	indel.6102	T	CT	.	PASS	.	GT:GQ	0/0:2
> chr1	145892823	indel.6130	T	CTCTTT	.	PASS	.	GT:GQ	0/0:3
> chr1	145873621	indel.6147	TG	G	.	PASS	.	GT:GQ	0/0:2
> chr1	145873607	indel.6148	G	TG	.	PASS	.	GT:GQ	0/0:3
> chr1	145872926	1KG_1_145562155	T	CCTT	.	PASS	.	GT:GQ	0/0:2
> chr1	145867368	indel.6157	TG	G	.	PASS	.	GT:GQ	0/0:3
> chr1	145838109	indel.6181	TAG	G	.	PASS	.	GT:GQ	0/0:2
> chr1	145826589	indel.6187	AC	C	.	PASS	.	GT:GQ	0/0:3
> chr1	145736151	indel.6189	CGTAAGCACCCCAAGCA	A	.	PASS	.	GT:GQ	0/0:3
> chr1	145731005	indel.6192	GT	T	.	PASS	.	GT:GQ	0/0:3
> chr1	145686476	indel.6198	C	AC	.	PASS	.	GT:GQ	0/0:6
> chr1	144423146	var_1_148594506	TG	G	.	PASS	.	GT:GQ	0/0:2
> chr1	206016023	indel.9616	G	AGGAG	.	PASS	.	GT:GQ	0/0:3
> chr10	47355450	indel.12475	TG	G	.	PASS	.	GT:GQ	0/0:2
> chr10	47353516	indel.12476	GT	T	.	PASS	.	GT:GQ	0/0:3
> chr10	46010865	indel.12613	TC	C	.	PASS	.	GT:GQ	0/0:2
> chr11	54707629	indel.17968	G	TG	.	PASS	.	GT:GQ	0/0:3
> chr11	54707548	indel.17970	CT	T	.	PASS	.	GT:GQ	0/0:3
> chr11	54603389	indel.17972	T	AT	.	PASS	.	GT:GQ	0/0:2
> chr11	54603365	indel.17973	G	CAG	.	PASS	.	GT:GQ	0/0:2
> chr15	23030984	indel.34217	GTTGA	A	.	PASS	.	GT:GQ	0/0:2
> chr15	23021965	indel.34223	C	GC	.	PASS	.	GT:GQ	0/0:3
> chr15	23011305	indel.34227	G	AG	.	PASS	.	GT:GQ	0/0:2
> chr21	10592374	indel.69325	GT	T	.	PASS	.	GT:GQ	0/0:1
> ```
> 
> But now we have ... I can't understand, what do we have now. Some random alleles.
> 
> ```
> chr1	149032050	indel.6062	GT	C	.	PASS	.	GT:GQ	0/0:3
> chr1	148974590	indel.6073	AG	T	.	PASS	.	GT:GQ	0/0:3
> chr1	148953847	indel.6081	CA	G	.	PASS	.	GT:GQ	0/0:2
> chr1	148953579	indel.6083	GA	C	.	PASS	.	GT:GQ	0/0:3
> chr1	145994150	indel.6100	C	TG	.	PASS	.	GT:GQ	0/0:2
> chr1	145994018	indel.6101	CAGTATA	G	.	PASS	.	GT:GQ	0/0:2
> chr1	145994017	indel.6102	T	CA	.	PASS	.	GT:GQ	0/0:2
> chr1	145892823	indel.6130	T	CTCTTA	.	PASS	.	GT:GQ	0/0:3
> chr1	145873621	indel.6147	TG	A	.	PASS	.	GT:GQ	0/0:2
> chr1	145873607	indel.6148	G	TC	.	PASS	.	GT:GQ	0/0:3
> chr1	145872926	1KG_1_145562155	T	CCTA	.	PASS	.	GT:GQ	0/0:2
> chr1	145867368	indel.6157	TG	A	.	PASS	.	GT:GQ	0/0:3
> chr1	145838109	indel.6181	TAG	A	.	PASS	.	GT:GQ	0/0:2
> chr1	145826589	indel.6187	AC	T	.	PASS	.	GT:GQ	0/0:3
> chr1	145736151	indel.6189	CGTAAGCACCCCAAGCA	G	.	PASS	.	GT:GQ	0/0:3
> chr1	145731005	indel.6192	GT	C	.	PASS	.	GT:GQ	0/0:3
> chr1	145686476	indel.6198	C	AG	.	PASS	.	GT:GQ	0/0:6
> chr1	144423146	var_1_148594506	TG	A	.	PASS	.	GT:GQ	0/0:2
> chr1	206016023	indel.9616	G	AGGAC	.	PASS	.	GT:GQ	0/0:3
> chr10	47355450	indel.12475	TG	A	.	PASS	.	GT:GQ	0/0:2
> chr10	47353516	indel.12476	GT	C	.	PASS	.	GT:GQ	0/0:3
> chr10	46010865	indel.12613	TC	A	.	PASS	.	GT:GQ	0/0:2
> chr11	54707629	indel.17968	G	TC	.	PASS	.	GT:GQ	0/0:3
> chr11	54707548	indel.17970	CT	G	.	PASS	.	GT:GQ	0/0:3
> chr11	54603389	indel.17972	T	AA	.	PASS	.	GT:GQ	0/0:2
> chr11	54603365	indel.17973	G	CAC	.	PASS	.	GT:GQ	0/0:2
> chr15	23030984	indel.34217	GTTGA	C	.	PASS	.	GT:GQ	0/0:2
> chr15	23021965	indel.34223	C	GG	.	PASS	.	GT:GQ	0/0:3
> chr15	23011305	indel.34227	G	AC	.	PASS	.	GT:GQ	0/0:2
> chr21	10592374	indel.69325	GT	C	.	PASS	.	GT:GQ	0/0:1
> ```
> 
> Fortunately its only ~20 indels across 10000 indels in our data but this is still a problem.
> 
> Btw - I'm using `https://hgdownload.cse.ucsc.edu/goldenpath/hg19/liftOver/hg19ToHg38.over.chain.gz` chain - should I use `ftp://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh37_to_GRCh38.chain.gz` instead?


@liguowang [link](https://github.com/liguowang/CrossMap/issues/44#issuecomment-1273567746)
> To be honest, I don't know which one (**chr1:149032050 GT->T** or **chr1:149032049 GG->G**) is correct. But for the 2nd one (chr1:149032049 GG->G) would NOT tell you which reference G is deleted. right?


@Stikus [link](https://github.com/liguowang/CrossMap/issues/44#issuecomment-1273602651)
> According to spec - second one is correct because only it has correct ALT in POS. And how can you differentiate which one G is deleted in nature? Aren't they the same?


@liguowang [link](https://github.com/liguowang/CrossMap/issues/44#issuecomment-1273633535)
> I agree. The 2nd one follows the VCF specification. This should be an easy fix.


@liguowang [link](https://github.com/liguowang/CrossMap/issues/44#issuecomment-1556466006)
> According to [VCF specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf) (Section 5.1.1 Example 1), the _first nucleotide of ALT_ should always be the same as _the first nucleotide of REF_. right? If this is true, the variants below are NOT valid:
> 
> chr1 149032050 indel.6062 GT T . PASS . GT:GQ 0/0:3 chr1 148974590 indel.6073 AG G . PASS . GT:GQ 0/0:3 chr1 148953847 indel.6081 CA A . PASS . GT:GQ 0/0:2 chr1 148953579 indel.6083 GA A . PASS . GT:GQ 0/0:3 ...


@Stikus [link](https://github.com/liguowang/CrossMap/issues/44#issuecomment-1556675034)
> Yes, you are correct - these variants are incorrectly written in VCF. We have this conversation from [here](https://github.com/liguowang/CrossMap/issues/44#issuecomment-1273567746) - **chr1:149032050 GT->T** should be **chr1:149032049 GG->G**. But at least we can understand these deletions.
> 
> In old versions deletions have _**last** nucleotide of ALT_ same as the _**last** nucleotide of REF_, but correct will be **first**, as you pointed out.

**Comment by serge2016** [comment]
Hope to see the solution soon! Thank you for the CrossMap!

**Comment by liguowang** [comment]
Just use one example to show the complexity. I don't know how to deal with this variant. 

# one input variant in VCF file (hg19/GRCh37):
chr1	   145382743	rs782203468	**G  	GA**	.	PASS	.

# expected output-1 (based on dbSNP and by previous users)
chr1	   146052257	rs782203468	**C	CA**	.	PASS	.
(this is also problematic, as it only reverse complements the REF allele, keep the ALT allele the same ??)

# output by CrossMap (converted to hg38/GRCh38)
chr1	   146052257	rs782203468	**C	TG**	.	PASS	.

The output of CrossMap is not correct, because the 1st nucleotide of REF and ALT should be the same. However, in this particular region, the hg19 was corresponding to the reverse strand of hg38. And because of this, CrossMap changed "CA" into "TG". Again, this is invalid for this particular variant, but if I turn off the reverse complement step, other variants might be affected.

# expected output-2
chr1	146052257	rs782203468	**C	CT**	.	PASS	.
(In this case, both REF and ALT alleles are reverse complemented)

Which one is correct? expected output-1  or expected output-2?

**Comment by Stikus** [comment]
I'm confused - according to dbSNP: https://www.ncbi.nlm.nih.gov/snp/rs782203468
![image](https://github.com/liguowang/CrossMap/assets/41360525/45375c2a-ef76-46af-8150-84adb6993d37)

This variant has different description and I cannot find it on `hg38` in internet. Closest is https://www.ncbi.nlm.nih.gov/snp/rs1286863316 - but this is SNP (not indel) and shouldn't be a problem.

If `rs782203468` is duplication of nucleotide in `145382744` position - looks like in `hg38` it should be `chr1 146052258 T -> TT`? Which is same as `chr1 146052257 C -> CT`.

Where do you find the reason behind output-1?

**Comment by liguowang** [comment]
The expected output-1 is reported by @ivan-mh.  you can also search rs782203468 using the UCSC genome browser (hg38)



> Hi Liguo,
> 
> Thank you very much for releasing CrossMap version 0.6.3. I now run the full test with more than 600 million DBSNP v151 variants.
> 
> With CrossMap version 0.6.1, I found 930 problematic variants targeted in this issue. With the new version, I am still unfortunately getting 109 problematic variants, which is a big improvement, although the problem now seems to be for variants on the negative strand on GRCh38.
> 
> Example: ![image](https://user-images.githubusercontent.com/54623677/158888970-d5743972-4f71-4f90-b74f-35170fe5d509.png)
> 
> For GRCh37 input variant: chr7 61879851 rs1223781306 A AC . . .
> 
> I would expect according to DBSNP on GRCh38: chr7 62217710 rs1223781306 T TG . . .
> 
> Nevertheless, I got from CrossMap on GRCh38: chr7 62217710 . T GA . . .
> 
> The problem seems to be that an insertion turns into a delins, which does not seem to be correct. The REF and ALT should start with the REF nucleotide T at position chr7:62217710 on GRCh38. Would it be possible to fix also such variants?
> 
> Attached is a file containing all the 109 problematic variants, where INFO.GRCh37 is the input GRCh37 variant in format CHROM:POS:REF:ALT. Fields CHROM, POS, REF, ALT contain the CrossMap v0.6.3 output on GRCh38. The ID contains the expected mapping according to DBSNP on GRCh38 in format: s;RS;GENE;CHROM:POS:REF:ALT, where the ALT can contain multiple values for one RS identifier. I am also aware that not all expected DBSNP variant mappings are correct according to the chain file I am using, where I am using: ftp://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh37_to_GRCh38.chain.gz
> 
> Best wishes, Ivan [CrossMap_v063_issue_44.txt](https://github.com/liguowang/CrossMap/files/8291611/CrossMap_v063_issue_44.txt)

**Comment by Stikus** [comment]
@liguowang  Thank you for answer, I've found data for rs782203468 [here](https://genome-euro.ucsc.edu/cgi-bin/hgc?hgsid=311772195_LJZowVJANMTA1gpAUGdI10ux3ed9&db=hg38&c=chr1&l=146052007&r=146052507&o=146052257&t=146052257&g=snp151&i=rs782203468) and in our downloaded dbSNP v151:
```
bio@bisa07:/mnt/ubm01-raid10/annotations$ grep rs782203468 All_20180418.vcf
1       146052257       rs782203468     C       CA      .       .       RS=782203468;RSPOS=146052257;dbSNPBuildID=144;SSR=0;SAO=0;VP=0x050000020005000002000200;GENEINFO=RNVU1-6:101954276|LINC01719:101928979;WGT=1;VC=DIV;R5;ASP
```

But now dbsnp doesn't have this info, as you can see here: https://www.ncbi.nlm.nih.gov/snp/rs782203468

We have discussion with colleagues, and we think that it is correct to use output-2 (due to logic behind it).

You cannot simply translate every variant from old GRCh37 dbSNP to modern GRCh38 dbSNP due to major changes in variants like:
```
chr22	22060260	s;rs1167216219;INTERGENIC;chr22:22060260:GA:G	GA	TA	.	.	TYPE=indel;GRCh37=chr22:22414672:TG:TA
```
https://www.ncbi.nlm.nih.gov/snp/rs1167216219/ is now `delA` but it was `G -> A`:
![image](https://github.com/liguowang/CrossMap/assets/41360525/e77312a6-c3cf-4cb9-836a-d8dcc7fe96d1)

@ivan-mh What do you think?

**Comment by Stikus** [comment]
@liguowang Hello, thx for new release.

I found a minor problem with incorrect version (`0.6.6`, not `0.7.0`):  
`##liftOverProgram=CrossMap,version=0.6.6,website=https://crossmap.readthedocs.io/en/latest/`

And several changes in file (left is new):
![image](https://github.com/liguowang/CrossMap/assets/41360525/f5ce1832-6a7f-4668-b42e-2d44e7c31842)

According to VCF spec - new indels are correctly written, but I think that they are incorrect:

Let's test `indel.6062`:

- `GRCh37 file` https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg19 :

```
1	144852392	indel.6062	AC	A	.	PASS	.	GT:GQ	0/0:3
```
![image](https://github.com/liguowang/CrossMap/assets/41360525/63699b63-fc79-4d0a-8cea-c88bca44f821)

- `GRCh38 file` (first string - old file, second - new) :
```
chr1	149032050	indel.6062	GT	T	.	PASS	.	GT:GQ	0/0:3
chr1	149032050	indel.6062	GT	G	.	PASS	.	GT:GQ	0/0:3
```
![image](https://github.com/liguowang/CrossMap/assets/41360525/b45e57b9-1aee-48df-96f0-1e1947d0404f)

So if this is reverse complement region in GRCh38, and it was deletion of `C` - this should be deletion of `G`. Old file was incorrectly written, but deletion was correct.
In new file, you should change position to minus one - `chr1	149032049 GG G `.

It's easier to see on long deletion `indel.6189`:
- `GRCh37 file`:
```
1	145698920	indel.6189	TGCTTGGGGTGCTTACG	T	.	PASS	.	GT:GQ	0/0:3
```
![image](https://github.com/liguowang/CrossMap/assets/41360525/d4d1cf5b-d237-4838-9eb6-b6f7896c8fb9)


- `GRCh38 file` (first string - old file, second - new) :
```
chr1	145736151	indel.6189	CGTAAGCACCCCAAGCA	A	.	PASS	.	GT:GQ	0/0:3
chr1	145736151	indel.6189	CGTAAGCACCCCAAGCA	C	.	PASS	.	GT:GQ	0/0:3
```
![image](https://github.com/liguowang/CrossMap/assets/41360525/7f4edff9-1ccf-4c37-90b4-11c24478f68a)

This is reverse complement regions and if in GRCh37 first `T` was left - in GRCh38 last `A` should be left:
![image](https://github.com/liguowang/CrossMap/assets/41360525/5bbfa819-532c-451b-a6d1-9249b4f22d20)

Thats why I assume correct variant is `chr1	145736150	CCGTAAGCACCCCAAGC	C` - again - minus one coordinate.

**Comment by liguowang** [comment]
I just uploaded two files ("src/cmmodule/mapvcf.py" and "src/cmmodule/mapgvcf.py") to github. Nothing else changed.  If you could just re-install from github, you should be able to test:

Input VCF variants (hg19)
---------------------------
1       144852392       indel.6062      AC      A       .       PASS    .       GT:GQ   0/0:3
1       145698920       indel.6189      TGCTTGGGGTGCTTACG       T       .       PASS    .       GT:GQ   0/0:3

Input VCF variants (hg38)
---------------------------
1       149032049       indel.6062      GG      G       .       PASS    .       GT:GQ   0/0:3
1       145736150       indel.6189      CCGTAAGCACCCCAAGC       C       .       PASS    .       GT:GQ   0/0:3

I hope I did not mess up other variants (which I have not tested yet). please let me know.

Thanks

**Comment by Stikus** [comment]
Thanks for fast update, results after testing:

Version still same (`0.6.6`), I assume it came from https://github.com/liguowang/CrossMap/blob/master/src/cmmodule/meta_data.py#L6

And about variants - unfortunately there are a lot of undesired changes - not tested all, but first test signals that changes are wrong:

- Left (old), right (new):

![image](https://github.com/liguowang/CrossMap/assets/41360525/430886fc-b80c-4991-b840-89baf8482303)

- GRCh37:

![image](https://github.com/liguowang/CrossMap/assets/41360525/46f2afbb-30d3-4157-9e3d-9c89467b4b97)

- `exm89960` (old was correct):

![image](https://github.com/liguowang/CrossMap/assets/41360525/6b9db7e1-612a-47de-b03d-8ba479dc2f8f)
![image](https://github.com/liguowang/CrossMap/assets/41360525/74969692-be8e-42ec-b764-0599f04be6a9)

- `indel.6062` (new is correct) - described earlier

- `exm90044` and `exm90045` (old was correct):

![image](https://github.com/liguowang/CrossMap/assets/41360525/14314b46-ca78-48e7-8808-4f7cf94bb889)

![image](https://github.com/liguowang/CrossMap/assets/41360525/ade033dd-bcf7-4655-b3fa-5dc68966f939)

At first look wrong variants are SNP's, not indels, and before we have a problem only with indels. Maybe you should exclude SNP's from your last change?

**Comment by serge2016** [comment]
@liguowang help us, please...

**Comment by liguowang** [comment]
> @liguowang Hello, any news?

Sorry, Not yet. Was busy recently.

**Comment by Stikus** [comment]
@liguowang Hello, still no progress?

**Comment by liguowang** [comment]
Will try one more time tonight. Thanks

**Comment by liguowang** [comment]
@Stikus 
I tested 5 variants below, and they all seem correctly converted into hg38. Before I upload the code, could you provide a few more examples (and your expected output) to test? Thanks

#Input variants (hg19/GRCh37)
chr22	28084772	test_001	CT	C	.	.	.
chr7	61879851	rs1223781306	A	AC	.	.	.
chr1	145382743	rs782203468	G	GA	.	.	.
chr1	144852392	indel.6062	AC	A	.	.	.
chr1	145698920	indel.6189	TGCTTGGGGTGCTTACG	T	.	.	.

#Output varints (hg38/GRCh38)
chr22	27688775	test_001	GT	G	.	.	.
chr7	62217710	rs1223781306	T	TG	.	.	.
chr1	146052257	rs782203468	C	CT	.	.	.
chr1	149032049	indel.6062	GG	G	.	.	.
chr1	145736150	indel.6189	CCGTAAGCACCCCAAGC	C	.	.	.

**Comment by Stikus** [comment]
@liguowang Thx for tests, I'll return with our results on Monday.

**Comment by liguowang** [comment]
I just updated the mapvcf.py and mapgvcf.py to github. You can try if the new version work for your problematic variants or not.

**Comment by Stikus** [comment]
Thx for updates, I've tested new code, looks like deletions are good now.
I have some questions about insertions and try to test more, but current version is definitely better, than previous.

A lot of changed insertions looks like their variant moved from start to end - e.g. `G->CAG` changed to `G->GCA` which is correctly stated but should not be correct every time. My test cases are in regions with a lot of repeats - that's why I need more time to test.

Here are my current results (comparison with old version with incorrectly stated variants from the beginning of this thread):
![image](https://github.com/liguowang/CrossMap/assets/41360525/de9e9b55-29e4-451a-9abd-a6f4dc421cc3)

**Comment by Stikus** [comment]
@liguowang Hello, any news? We can move to separate issue due to deletions looks fixed now, if you want.

**Comment by liguowang** [comment]
@Stikus Could you provide a few examples (the more the better) with

- The original variant
- The incorrect output
- Your expected (correct) output

I am busy but I can still find some time to work on it. 

Thanks

**Comment by Stikus** [comment]
Hello @liguowang , we are back to using Crossmap, looks like you have some major updates, but problem with insertions are still here:

<img width="1964" height="76" alt="Image" src="https://github.com/user-attachments/assets/f6401436-d66c-423e-8b4f-15925d7a93bb" />

- `CrossMap 0.7.4`: `chr1	145994150	indel.6100	C	CT`
- Correct should be: `chr1	145994149	indel.6100	T	TT`

Moreover - `chr1	145994018	indel.6101	CAGTATA	A	.	PASS	.	GT:GQ	0/0:2` is now moved to unmap file:
`1	145441045	indel.6101	TATACTG	T	.	PASS	.	GT:GQ	0/0:2	Fail(REF==ALT)`

I've even enabled `--no-comp-alleles` but this doesn't help (for some reason it doesn't change output at all on commit d14edd6d1d237bc221962dd325275fb2ff0a5f37) - maybe due to https://github.com/liguowang/CrossMap/blob/master/src/cmmodule/mapvcf.py#L279-L297 path of code - both 
```py
                if len(alt_alleles_updated) == 0:
                    print(line + "\tFail(REF==ALT)", file=UNMAP)
```
and 
```py
                if noCompAllele:
                    print('\t'.join(map(str, fields)), file=FILE_OUT)
                else:
                    if fields[3] != fields[4]:
                        print('\t'.join(map(str, fields)), file=FILE_OUT)
                    else:
                        print(line + "\tFail(REF==ALT)", file=UNMAP)
                        fail += 1
```
prints `Fail(REF==ALT)` to unmap file, but first doesn't take in account `--no-comp-alleles`

**Comment by liguowang** [comment]
for your variant (indel.6100), what is the original coordinates and
reference build? and to which reference build you would like to liftover? I
need this info to repeat your analysis.

Thanks

Liguo

**Comment by Stikus** [comment]
Original data (GRCh37):
```
1	145440919	indel.6100	G	GA	.	PASS	.	GT:GQ	0/0:2
1	145441045	indel.6101	TATACTG	T	.	PASS	.	GT:GQ	0/0:2
1	145441052	indel.6102	A	AG	.	PASS	.	GT:GQ	0/0:2
```
We are liftovering to GRCh38 (https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files)

**Comment by Stikus** [comment]
@liguowang Hello, any updates on topic?
